import type { TaskCard, Team } from "./domain";

const now = new Date();
export const demoTasks: Array<TaskCard & { id: string; score: number; readinessLevel: TaskCard["readinessLevel"]; confirmed: boolean; published: boolean; createdAt: Date; updatedAt: Date }> = [
  { id: "task-support", title: "AI-помощник для техподдержки", category: "AI / IT", originalDescription: "Автоматизировать первую линию поддержки.", context: "Служба поддержки получает повторяющиеся обращения через почту и внутренний портал.", need: "Снизить нагрузку на операторов и ускорить первый ответ клиенту.", users: "Клиенты и 12 операторов первой линии.", dataMaterials: "FAQ, 2 000 обезличенных тикетов и база знаний в Markdown.", constraints: "Данные нельзя передавать во внешние системы; интерфейс на русском языке.", expectedResult: "Прототип помощника, который классифицирует вопрос и предлагает оператору ответ.", successCriteria: "Не менее 70% типовых обращений классифицируются верно, время ответа сокращается на 30%.", contact: "Демо-куратор бизнеса", interactionFormat: "Две короткие встречи в неделю и чат для вопросов.", score: 96, readinessLevel: "Приоритетная", confirmed: true, published: true, createdAt: now, updatedAt: now },
  { id: "task-analytics", title: "Прогноз загрузки торговых точек", category: "Data Analytics", originalDescription: "Нужен прогноз трафика.", context: "Сеть планирует смены вручную и сталкивается с очередями в часы пик.", need: "Предсказывать загрузку на неделю вперёд по каждой точке.", users: "Региональные менеджеры и управляющие магазинов.", dataMaterials: "История чеков за 18 месяцев, календарь акций и погода.", constraints: "Результат должен работать на обезличенных данных.", expectedResult: "Дашборд с почасовым прогнозом и рекомендациями по сменам.", successCriteria: "Средняя ошибка прогноза не более 15% на тестовой выборке.", contact: "Продуктовый менеджер", interactionFormat: "Еженедельное демо", score: 88, readinessLevel: "Готовая", confirmed: true, published: true, createdAt: now, updatedAt: now },
  { id: "task-fintech", title: "Поиск аномалий в платежах", category: "FinTech", originalDescription: "Найти подозрительные платежи.", context: "Финансовая команда проверяет отчёты вручную после закрытия дня.", need: "Подсвечивать нетипичные операции для проверки аналитиком.", users: "Финансовые аналитики.", dataMaterials: "Обезличенная таблица транзакций за шесть месяцев.", constraints: "Только объяснимые признаки, без автоматической блокировки.", expectedResult: "Ранжированный список аномалий с объяснением факторов.", successCriteria: "", contact: "Финансовый контролёр", interactionFormat: "Одна встреча в неделю", score: 72, readinessLevel: "Готовая", confirmed: true, published: true, createdAt: now, updatedAt: now },
  { id: "task-education", title: "Навигатор учебных материалов", category: "Education", originalDescription: "Помочь студентам находить материалы.", context: "Материалы по курсам хранятся в разных папках и системах.", need: "Сделать единый поиск по темам и уровню сложности.", users: "Студенты первого курса.", dataMaterials: "Список ссылок и описания 120 материалов.", constraints: "", expectedResult: "Поиск и подборка материалов по запросу студента.", successCriteria: "", contact: "", interactionFormat: "", score: 56, readinessLevel: "Рабочая", confirmed: true, published: true, createdAt: now, updatedAt: now },
  { id: "task-docs", title: "Автоматизация заявок на документы", category: "Automation", originalDescription: "Упростить заявки сотрудников.", context: "Заявки поступают в свободной форме и теряются в переписке.", need: "Собирать заявки в едином структурированном виде.", users: "Сотрудники компании.", dataMaterials: "", constraints: "", expectedResult: "Прототип формы и реестра заявок.", successCriteria: "", contact: "", interactionFormat: "", score: 38, readinessLevel: "Черновик", confirmed: true, published: true, createdAt: now, updatedAt: now },
];

export const demoTeams: Team[] = [
  { id: "team-orbit", name: "Orbit AI", interests: "AI, Support", skills: "ML, UX, Backend", technologies: "Python, React, FastAPI" },
  { id: "team-delta", name: "Delta Data", interests: "Analytics", skills: "Data science, BI", technologies: "Python, SQL, Power BI" },
  { id: "team-pulse", name: "Pulse Lab", interests: "FinTech", skills: "Anomaly detection", technologies: "Python, TypeScript" },
  { id: "team-edunova", name: "EduNova", interests: "Education", skills: "Product, NLP", technologies: "Next.js, OpenAI" },
  { id: "team-flow", name: "Flow Makers", interests: "Automation", skills: "Full-stack, process design", technologies: "React, Node.js" },
];

export const demoProposals = [
  { id: "proposal-1", taskId: "task-support", teamId: "team-orbit", solutionIdea: "RAG-помощник, который ищет ответ в базе знаний и показывает источники оператору.", plan: "Подготовка данных, прототип поиска, интерфейс оператора, оценка на тестовых тикетах.", estimatedTime: "3 недели", prototypeUrl: "https://example.com/orbit-demo", status: "PENDING", createdAt: now },
  { id: "proposal-2", taskId: "task-analytics", teamId: "team-delta", solutionIdea: "Прогноз временных рядов с учётом акций и календарных факторов.", plan: "EDA, baseline, валидация, интерактивный дашборд.", estimatedTime: "4 недели", prototypeUrl: "", status: "ACCEPTED", createdAt: now },
  { id: "proposal-3", taskId: "task-fintech", teamId: "team-pulse", solutionIdea: "Гибрид правил и isolation forest с понятным вкладом признаков.", plan: "Профилирование, модель, объяснения, экран проверки.", estimatedTime: "3 недели", prototypeUrl: "", status: "PENDING", createdAt: now },
  { id: "proposal-4", taskId: "task-education", teamId: "team-edunova", solutionIdea: "Семантический каталог с фильтрами по теме и сложности.", plan: "Таксономия, индекс, поиск, пользовательское тестирование.", estimatedTime: "2 недели", prototypeUrl: "", status: "REJECTED", createdAt: now },
  { id: "proposal-5", taskId: "task-docs", teamId: "team-flow", solutionIdea: "Конструктор заявки и прозрачный канбан статусов.", plan: "Карта процесса, формы, реестр, демонстрация.", estimatedTime: "10 дней", prototypeUrl: "", status: "PENDING", createdAt: now },
] as const;
